spring.application.name=online-shop


spring.datasource.url=jdbc:mysql://localhost:3306/online_shop
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

online.shop.upload.image.directory,path=C:\\Users\\Admin\\IdeaProjects\\online-shop\\upload_images\\
